name: Github Actions Distributor
description: Distribute Github Actions to other repositories
author: 'ezqy'
inputs:
  org:
    description: 'The organization to distribute to'
    required: true
  repo:
    description: 'The repository to distribute to'
    required: true
  config:
    description: 'The configuration file'
    required: false
    default: .action-distributor/config.json
runs:
  using: 'node16'
  main: 'dist/action/index.js'
  post-if: success()