name: test

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'config file path'
        required: true
        default: .action-distributor/config.json

env:
  CONFIG_PATH: ${{ github.event.inputs.config }}

jobs:
  list:
    runs-on: ubuntu-latest
    env:
      owner: tc3-japan
    outputs:
      token: ${{ steps.generate_token.outputs.token }}
      target: ${{ steps.list.outputs.result }}
      owner: ${{ env.owner }}
    steps:
      - uses: actions/checkout@v3
      - id: list
        uses: actions/github-script@v6
        with:
          script: |
            const { CONFIG_PATH } = process.env
            const config = require(CONFIG_PATH);
            return Object.keys(config[process.env.owner])

  distribute:
    needs: list
    env:
      app_id: ${{ secrets.app_id }}
      private_key: ${{ secrets.private_key }}
    strategy:
      matrix:
        target: ${{ fromJson(needs.list.outputs.target) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: generate_token
        uses: ezqy/ghaction/generate-github-app-token@v1.0.0
        with:
          app_id: ${{ env.app_id }}
          private_key: ${{ env.private_key }}
      - uses: ezqy/action-distributor@main
        with:
          owner: ${{ needs.list.outputs.owner }}
          repo: ${{ matrix.target }}
          config: ${{ env.CONFIG_PATH }}
        env:
          GH_TOKEN: ${{ needs.list.outputs.token }}
          